### ISSUE TITLE
Feature request: Pass options in config file

### ISSUE THREAD

**Issue by fsteggink** [justb4/stetl#22]
Stetl is having its configuration delivered in two different ways currently. A config file is delivered through the command line, but also many options are passed at the command line, through the -a parameter.

For example with TOP10extract (NLExtract):
python $STETL_HOME/stetl/main.py -c etl-top10nl.cfg -a "$pg_options temp_dir=temp max_features=$max_features gml_files=$gml_files $multi $spatial_extent"

The disadvantage of this approach is that the options are generated with shell scripting. This has a drawback on the portability of Stetl to other platforms, like Windows. (As far as I can tell, there are no other issues, although I've currently run Stetl only through MingW MSYS.)

Of course there is still a use case to have Stetl accept the -a command line option, but in many cases a the options which are passed through -a do not change.

**Comment by justb4** [comment]
Still work needed on this issue? I use it already in all new ETL configs. Possibly some documentation in .rst still...

**Comment by justb4** [comment]
Think we can close this one. Already in use in some configs like NLExtract BRK:
https://github.com/opengeogroep/NLExtract/tree/master/brk/etl
