### ISSUE TITLE
Are LCO options always executed when expected?

### ISSUE THREAD

**Issue by fsteggink** [justb4/stetl#30]
While working on Stetl I was wondering whether the LCO options are always executed when necessary, as expected. This appears not to be the case in my current version (see PR #28), using the Ogr2OgrExecOutput. The LCO options are only passed once. The problem is that you don't exactly when these options need to be executed, and I think this is also the issue with the current Ogr2OgrOutput.

For example, when the BRT is loaded (using file chunks), a temporary GML file is being created, which is then being loaded by ogr2ogr. This GML file doesn't necessarily contain all the feature types which can be found in BRT. Ogr2ogr only creates the tables (when loading in PostGIS) for the features occurring in the temporary GML file. So, on subsequent runs of ogr2ogr, new tables can be created, but in those cases the LCO options are not applied anymore.

**Comment by justb4** [comment]
Yes, it is true that LCO is only passed to ``ogr2ogr`` on the first run. Not really sure why, but think something went wrong when passing LCO in all runs. Yes, the feature types present may be totally different (think of some BRT distributions). Hence I would always recommend using GFS files in these cases, as we do. Does this answer your question and can we close the issue?

**Comment by justb4** [comment]
I guess we can close. Please reopen if needed.
